version: '3'

services:
  jenkins:
    container_name: jenkins3
    image: jenkins/jenkins:lts
    ports:
      - "9999:8080"
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins:/var/jenkins_home
    restart: always
    environment:
        TZ: "Asia/Seoul"
    user: root